### ISSUE TITLE
GitHub Actions: pypy3 tests on Windows fails

### ISSUE THREAD

**Issue by sajith** [tahoe-lafs/zfec#38]
See [this run](https://github.com/tahoe-lafs/zfec/pull/37/checks?check_run_id=1383070410#step:6:79), for example.  It fails with:

```
Run tox -e py
___________________________________ summary ___________________________________
ERROR:   py: undefined
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\__init__.py", line 25, in get_executable
    return self.name2executable[envconfig.envname]
KeyError: 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib-python\3\runpy.py", line 196, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib-python\3\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\PyPy\3.6.9\x86\bin\tox.exe\__main__.py", line 7, in <module>
    sys.exit(cmdline())
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\session\__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\session\__init__.py", line 197, in runcommand
    return self.subcommand_test()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\session\__init__.py", line 225, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\session\commands\run\sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\venv.py", line 615, in setupenv
    with self.new_action("getenv", self.envconfig.envdir) as action:
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\venv.py", line 135, in new_action
    self.envconfig.envpython,
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\config\__init__.py", line 1032, in envpython
    return self.get_envpython()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\config\__init__.py", line 1040, in get_envpython
    return self.envbindir.join(name)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\config\__init__.py", line 1027, in envbindir
    return self.get_envbindir()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\config\__init__.py", line 1014, in get_envbindir
    isinstance(self.python_info, NoInterpreterInfo)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\config\__init__.py", line 1053, in python_info
    return self.config.interpreters.get_info(envconfig=self)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\__init__.py", line 33, in get_info
    executable = self.get_executable(envconfig)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\__init__.py", line 27, in get_executable
    exe = self.hook.tox_get_python_executable(envconfig=envconfig)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\windows\__init__.py", line 14, in tox_get_python_executable
    spec, path = base_discover(envconfig)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\common.py", line 17, in base_discover
    cur_spec = exe_spec(discover, envconfig.basepython)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\via_path.py", line 38, in exe_spec
    info = get_python_info(python_exe)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\via_path.py", line 66, in get_python_info
    universal_newlines=True,
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib-python\3\subprocess.py", line 744, in __init__
    restore_signals, start_new_session)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib-python\3\subprocess.py", line 1045, in _execute_child
    startupinfo)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib_pypy\_winapi.py", line 321, in CreateProcess
    raise _WinError()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib_pypy\_winapi.py", line 30, in _WinError
    raise excep
OSError: [WinError 87] The parameter is incorrect
Error: Process completed with exit code 1.
```

**Comment by sajith** [comment]
Issue reported with tox: tox-dev/tox/issues/1740.
